project:
  type: website
  

website:
  title: "Introduction to {renv}"
  page-footer: 
    center: "Copyright 2024, Open Science Center at LMU München" 
    border: false
  search:
    location: navbar
    type: overlay
    collapse-after: 3
    copy-button: true
  repo-url: https://github.com/lmu-osc/introduction-to-renv
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/introduction-to-renv
          - text: Report a Bug
            url:  https://github.com/lmu-osc/introduction-to-renv/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html
   
        
  sidebar:
    style: "docked"
    contents:
      - section: "Tutorial"
        contents:
          - href: index.qmd
          - text: "Ex: Override text in yaml"
            href: intro_dependencies.qmd
          - href: dependencies_in_r.qmd
          - href: renv_getting_started.qmd
          - href: restoring_a_project.qmd
      - section: "Optional Content"
        contents: 
          - href: advanced_topics.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

