project:
  type: website
  

website:
  title: "Introduction to {renv}"
  page-footer: 
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/introduction-to-renv
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  favicon: assets/LMU-OSC_favicon.jpg
  margin-header: |
    ![](/assets/LMU-OSC_logo.jpg){width="175"}
  
  
  navbar:
    right: 
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/introduction-to-renv
          - text: Report a Bug
            url:  https://github.com/lmu-osc/introduction-to-renv/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html
   
        
  sidebar:
    style: "docked"
    # background: "#cfc7c6"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Background"
        contents:
          - href: comp_reproducible.qmd
            text: "1. Reproducibility"
          - href: intro_dependencies.qmd
            text: "2. Software Dependencies"
          - href: technical_definitions.qmd
            text: "3. Technical Definitions"
          - href: dependencies_in_r.qmd
            text: "4. R Package Managers"
      - section: "{renv}"
        contents:
          - href: renv_getting_started.qmd
            text: "1. Quick Start"
          - href: starting_details.qmd
            text: "2. Understanding {renv}"
          - href: restoring_a_project.qmd
            text: "3. Restoring Projects"
      - section: "Exercises"
        contents:
          - href: ex_init_snapshot.qmd
            text: "Init and Snapshot"
          - href: ex_2.qmd
            text: "Restore"
          - href: ex_3.qmd
            text: "Explicitly Record"
      - section: "Optional Content"
        contents: 
          - href: caching.qmd
            text: "Caching"
          - href: embed_and_use.qmd
            text: "`embed()` and `use()`"
          - href: advanced_topics.qmd


format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px


editor: source
csl: chicago-fullnote-bibliography.csl
