project:
  type: website
  

website:
  title: "Introduction to {renv}"
  page-footer: 
    center: "Copyright, 2024 Open Science Center at LMU Munich"
    border: false
  search:
    location: sidebar
  repo-url: https://github.com/lmu-osc/introduction-to-renv
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-navigation: true
  
  
  navbar:
    right: 
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/lmu-osc/introduction-to-renv
          - text: Report a Bug
            url:  https://github.com/lmu-osc/introduction-to-renv/issues
      - icon: house-heart
        url: https://www.osc.uni-muenchen.de/index.html
   
        
  sidebar:
    style: "docked"
    # background: "#cfc7c6"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Background"
        contents:
          - href: comp_reproducible.qmd
            text: "1. Reproducibility"
          - href: intro_dependencies.qmd
            text: "2. Software Dependencies"
          - href: dependencies_in_r.qmd
            text: "3. Dependencies in R"
      - section: "{renv}"
        contents:
          - href: renv_getting_started.qmd
            text: "1. Getting Started"
          - href: restoring_a_project.qmd
            text: "2. Restoring A Project"
      - section: "Exercises"
        contents:
          - href: ex_init_snapshot.qmd
            text: "Init and Snapshot"
          - href: ex_2.qmd
            text: "Exercise 2"
          - href: ex_3.qmd
            text: "Exercise 3"
      - section: "Optional Content"
        contents: 
          - href: advanced_topics.qmd
          - href: embed_and_use.qmd
            text: "`embed()` and `use()`"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    fontsize: 13pt
    code-overflow: wrap
    grid:
      sidebar-width: 300px


editor: visual

