---
title: "About"
date: 2024-11-27
citation:
  type: "webpage"
  title: "Introduction to {renv}"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/introduction-to-renv
  doi: "10.5281/zenodo.14230879"
  version: 0.2.0
author:
  - name: Pat Callahan
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0003-1769-7580
  - name: Florian Pargent
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0002-2388-553X
  - name: Florian Kohrt
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0003-0374-5625
# google-scholar: true
---

## Contributors

This site was authored by Pat Callahan with contributions and feedback from Florian Pargent and Florian Kohrt.

## Licenses

The overall project is available under the [**CC BY-SA 4.0**](https://creativecommons.org/licenses/by-sa/4.0/) license found at [LICENSE](LICENSE.md); all code without any narrative text is also (at your option) available under the [**CC0 1.0 Universal**](https://creativecommons.org/publicdomain/zero/1.0/) license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

## Notes

This tutorial was primarily written in 2024 using {renv} version 1.0.11. Major changes to the {renv} package are unlikely to occur in the near future, but it is always a good idea to check the [package's website](https://rstudio.github.io/renv/) for the most up-to-date information, and to confirm that our tutorial is not out-of-date.

## Tutorial Template Quarto Extension

This tutorial was written using the [`lmu-osc/tutorial-template`](https://github.com/lmu-osc/tutorial-template) Quarto extension [@callahan2026].

::: {#refs}
:::

## How to Cite

**To cite this tutorial, please refer to the project's [CITATION.cff](CITATION.cff) file or use the BibTeX citation provided in the appendix below.**
