---
title: "Welcome to the {renv} Tutorial!"
subtitle: A self-paced tutorial on reproducible R environments with the {renv} package
description: An introduction to the {renv} package for managing R package dependencies in reproducible projects.
---

```{r}
#| eval: true
#| echo: false
#| warning: false
library(downlit)
library(xml2)
```


## Tutorial Overview

This **self-paced tutorial** is intended to take 1-2 hours to complete, depending on your previous familiarity with the theoretical and programming components of dependency management and R. Content has been written with novice R users in mind, but this tutorial (hopefully) provides useful information on setting up reproducible computational environments for R users of any skill level.

The tutorial is split into the following sections:

1.  [**Background**](background/) introduces a simplified definition and reasoning for reproducibility, its relation to managing software dependencies, and some of the nuances of dependencies in R.
2.  [**{renv}**](about-renv/) discusses the main functions of the {renv} package, and just enough of the underlying mechanics of the package to be useful. **You can jump to this section if you don't have time for the background.**
3.  [**Exercises**](exercises/) contains a handful of practical exercises that walk users through the main components of using {renv}, and highlights some common mistakes or issues users might encounter.
4.  [**Optional Content**](extra-content/) dives into some of the more technical details of {renv}, caching, and related topics. This section is only recommended for users with more advanced use cases or troubleshooting needs.


::: {.callout-warning title="Recommended Software"}

This tutorial assumes you have the following software installed:

-   [R, recommend v4.4.X or more recent](https://www.r-project.org/){target="_blank"}
-   [RStudio](https://posit.co/download/rstudio-desktop/){target="_blank"}
-   {renv}, installed with `install.packages("renv")` from within R

Although optional for the general content in this tutorial, **knowledge of git and GitHub** will be helpful for the exercises especially if you would like to receive feedback or troubleshoot issues remotely. Check out [our git and GitHub tutorial](https://lmu-osc.github.io/Introduction-RStudio-Git-GitHub/) if needed!

:::


:::: {.columns}

::: {.column width="47.5%"}

::: {.callout-tip title="Support the LMU Open Science Center!"}

**Like this tutorial? Be sure to give [the repository]({{< meta repo-url >}}) a star and [follow us on GitHub](https://github.com/lmu-osc)!**
:::

:::

::: {.column width="5%"}
:::

::: {.column width="47.5%"}


::: {.callout-tip title="Questions about this tutorial?"}
**If you have questions for the author of this tutorial, please take a look at the [About](about.qmd) page.**
:::

:::

::::
